[SETTINGS]
; Keybind to toggle the Alien World Spawner menu (Default: PageDown)
; Common valid options: PageDown, F10, F9, F8, F7, F6, F5, F3, Insert, Delete, Home, End, I, O, K, L, etc.
MenuKey=PageDown

